### ISSUE TITLE
Exception when loading windows library on linux

### ISSUE THREAD

**Issue by sparr** [ShadelessFox/decima#51]
Attempting to follow the wiki instructions for Death Stranding leads to an exception when attempting to load the compressor library:

```
java.lang.IllegalStateException: java.lang.UnsatisfiedLinkError: Unable to load library '/home/sparr/.steam/steam/steamapps/common/DEATH STRANDING DIRECTORS CUT/oo2core_7_win64.dll':
/home/sparr/.steam/steam/steamapps/common/DEATH STRANDING DIRECTORS CUT/oo2core_7_win64.dll: invalid ELF header
/home/sparr/.steam/steam/steamapps/common/DEATH STRANDING DIRECTORS CUT/oo2core_7_win64.dll: invalid ELF header
Native library (home/sparr/.steam/steam/steamapps/common/DEATH STRANDING DIRECTORS CUT/oo2core_7_win64.dll) not found in resource path (/home/sparr/Downloads/decima/decima-0.1.12/lib/decima-0.1.12.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/decima-ui.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/platform-ui.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/decima-model.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/platform-model.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/logback-classic-1.4.4.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/gson-2.10.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/reflections-0.10.2.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/miglayout-swing-11.0.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/flatlaf-extras-2.6.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/flatlaf-2.6.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/jna-5.12.1.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/picocli-4.7.0.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/logback-core-1.4.4.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/slf4j-api-2.0.1.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/javassist-3.28.0-GA.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/jsr305-3.0.2.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/miglayout-core-11.0.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/svgSalamander-1.1.3.jar)
    at com.shade.platform.ui.controls.tree.TreeModel$LoadingWorker.done(TreeModel.java:345)
    at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
    at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:848)
    at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
    at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:858)
    at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
    at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library '/home/sparr/.steam/steam/steamapps/common/DEATH STRANDING DIRECTORS CUT/oo2core_7_win64.dll':
/home/sparr/.steam/steam/steamapps/common/DEATH STRANDING DIRECTORS CUT/oo2core_7_win64.dll: invalid ELF header
/home/sparr/.steam/steam/steamapps/common/DEATH STRANDING DIRECTORS CUT/oo2core_7_win64.dll: invalid ELF header
Native library (home/sparr/.steam/steam/steamapps/common/DEATH STRANDING DIRECTORS CUT/oo2core_7_win64.dll) not found in resource path (/home/sparr/Downloads/decima/decima-0.1.12/lib/decima-0.1.12.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/decima-ui.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/platform-ui.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/decima-model.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/platform-model.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/logback-classic-1.4.4.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/gson-2.10.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/reflections-0.10.2.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/miglayout-swing-11.0.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/flatlaf-extras-2.6.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/flatlaf-2.6.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/jna-5.12.1.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/picocli-4.7.0.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/logback-core-1.4.4.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/slf4j-api-2.0.1.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/javassist-3.28.0-GA.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/jsr305-3.0.2.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/miglayout-core-11.0.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/svgSalamander-1.1.3.jar)
    at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:307)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:467)
    at com.sun.jna.Library$Handler.<init>(Library.java:192)
    at com.sun.jna.Native.load(Native.java:622)
    at com.shade.decima.model.util.Compressor.<init>(Compressor.java:36)
    at com.shade.decima.model.app.Project.<init>(Project.java:44)
    at com.shade.decima.model.app.ProjectManagerImpl.openProject(ProjectManagerImpl.java:91)
    at com.shade.decima.ui.navigator.impl.NavigatorProjectNode.open(NavigatorProjectNode.java:35)
    at com.shade.decima.ui.navigator.impl.NavigatorProjectNode.loadChildren(NavigatorProjectNode.java:70)
    at com.shade.decima.ui.navigator.impl.NavigatorProjectNode.loadChildren(NavigatorProjectNode.java:23)
    at com.shade.platform.ui.controls.tree.TreeNodeLazy.getChildren(TreeNodeLazy.java:20)
    at com.shade.platform.ui.controls.tree.TreeModel.getChildren(TreeModel.java:285)
    at com.shade.platform.ui.controls.tree.TreeModel$LoadingWorker.doInBackground(TreeModel.java:322)
    at com.shade.platform.ui.controls.tree.TreeModel$LoadingWorker.doInBackground(TreeModel.java:309)
    at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
    at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.base/java.lang.Thread.run(Thread.java:1623)
    Suppressed: java.lang.UnsatisfiedLinkError: /home/sparr/.steam/steam/steamapps/common/DEATH STRANDING DIRECTORS CUT/oo2core_7_win64.dll: invalid ELF header
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:197)
        ... 19 more
    Suppressed: java.lang.UnsatisfiedLinkError: /home/sparr/.steam/steam/steamapps/common/DEATH STRANDING DIRECTORS CUT/oo2core_7_win64.dll: invalid ELF header
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:210)
        ... 19 more
    Suppressed: java.io.IOException: Native library (home/sparr/.steam/steam/steamapps/common/DEATH STRANDING DIRECTORS CUT/oo2core_7_win64.dll) not found in resource path (/home/sparr/Downloads/decima/decima-0.1.12/lib/decima-0.1.12.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/decima-ui.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/platform-ui.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/decima-model.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/platform-model.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/logback-classic-1.4.4.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/gson-2.10.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/reflections-0.10.2.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/miglayout-swing-11.0.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/flatlaf-extras-2.6.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/flatlaf-2.6.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/jna-5.12.1.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/picocli-4.7.0.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/logback-core-1.4.4.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/slf4j-api-2.0.1.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/javassist-3.28.0-GA.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/jsr305-3.0.2.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/miglayout-core-11.0.jar:/home/sparr/Downloads/decima/decima-0.1.12/lib/svgSalamander-1.1.3.jar)
        at com.sun.jna.Native.extractFromResourcePath(Native.java:1145)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:281)
        ... 19 more
```

There may be a way to get this working by loading the library through wine or proton. Or some of the functionality may be useful without the library?

**Comment by REDxEYE** [comment]
While you're waiting for @ShadelessFox response, I can suggest you to find linux version of Oodle library. It should be available in Linux builds of warframe or UE4/5 games

**Comment by ShadelessFox** [comment]
Hello @sparr,

Sorry, you can't use Windows' dynamic libraries (`.dll`) on Linux. You'll need one that was compiled for Linux (`.so`).

Death Stranding was only released on Windows, so you'll need to scrap it from another game, as @REDxEYE mentioned.

I'll update the wiki to mention issues for non-Windows users.
