### ISSUE TITLE
Unable to save changes

### ISSUE THREAD

**Issue by Stealch** [ShadelessFox/decima#55]
When i make changes /ds/entities/gimmick/structure/construction_rshl.core i couldn't save changes! I got a lot of errors:
java.lang.IllegalStateException: Can't determine size of Java class
    at com.shade.decima.model.rtti.registry.providers.JavaTypeProvider$JavaClass.getSize(JavaTypeProvider.java:121)
    at com.shade.decima.model.base.CoreBinary.lambda$serialize$0(CoreBinary.java:61)
    at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214)
    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:515)
    at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:473)
    at com.shade.decima.model.base.CoreBinary.serialize(CoreBinary.java:61)
    at com.shade.decima.ui.editor.core.CoreEditor.doSave(CoreEditor.java:266)
    at com.shade.decima.ui.menu.menus.FileMenu$SaveItem.perform(FileMenu.java:108)
    at com.shade.platform.ui.menus.impl.MenuManagerImpl.lambda$createMenuItem$1(MenuManagerImpl.java:244)
    at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
    at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
    at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
    at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
    at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
    at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
    at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
    at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
    at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
    at java.desktop/java.awt.Component.processEvent(Component.java:6391)
    at java.desktop/java.awt.Container.processEvent(Container.java:2266)
    at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
    at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
    at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
    at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
    at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
    at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
    at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
    at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
    at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
    at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
    at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by ShadelessFox** [comment]
Hello @Stealch,

I'm able to edit that file and repack against 0.1.14. What version are you using? It can be found under Help -> About

**Comment by Stealch** [comment]
> Hello @Stealch,
> 
> I'm able to edit that file and repack against 0.1.14. What version are you using? It can be found under Help -> About

I use 0.1.14 version from releases. I have no skills in Java to compile Decima Workshop from source code. I just use it "as is". I already successfully make one mod using your tool, but stuck with next one cause this error occurred.

**Comment by ShadelessFox** [comment]
Do you have multiple files edited? It might not be this one causing this issue.

Can you please provide a minimal reproducible example?

**Comment by Stealch** [comment]
> Do you have multiple files edited? It might not be this one causing this issue.
> 
> Can you please provide a minimal reproducible example?

I do not multiple files editing.
For example - i change radius of OdradekEffectSize (float) at line 7 and 8 from 4 to 9 and from 4 to 15 and change SnowInteractRadius from 4 to 9 at line 17

**Comment by ShadelessFox** [comment]
Are you working with the base game or Director's Cut?

Please ensure you have valid paths set for metadata files (`ds_xxx` for the base game, `dsdc_xxx` for Director's Cut) in the project:

![image](https://github.com/ShadelessFox/decima/assets/35821147/0cab271e-7b5c-427b-8d34-3d7d3503e314)

**Comment by ShadelessFox** [comment]
If you still experience issues, please join our Discord server to continue our discussion there: https://discord.gg/Gt4gkMwadB

**Comment by Stealch** [comment]
![2023-08-04_00-37-21](https://github.com/ShadelessFox/decima/assets/14859190/f3e680e3-a9a2-4571-ba69-d5484b29e685)
I have Director's cut version and all of paths and types right. I will join to discord now.

**Comment by ShadelessFox** [comment]
The issue was caused by using Director's Cut metadata files with the base game.
