### ISSUE TITLE
an error occurred during program exectution

### ISSUE THREAD

**Issue by Jomixedyu** [ShadelessFox/decima#63]
version: 0.1.18
jvm: 17.0.9
DEATH STRANDING DIRECTORS CUT

java.lang.IllegalArgumentException: Class 'UnknownEntry' has no field called 'EffectType'

java.lang.RuntimeException: java.lang.IllegalArgumentException: Class 'UnknownEntry' has no field called 'EffectType'
    at com.shade.decima.ui.data.viewer.model.ModelExportDialog.lambda$buttonPressed$2(ModelExportDialog.java:132)
    at com.shade.platform.ui.dialogs.ProgressDialog$1.doInBackground(ProgressDialog.java:47)
    at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.lang.IllegalArgumentException: Class 'UnknownEntry' has no field called 'EffectType'
    at com.shade.decima.model.rtti.RTTIClass.getField(RTTIClass.java:43)
    at com.shade.decima.model.rtti.objects.RTTIObject.get(RTTIObject.java:21)
    at com.shade.decima.model.rtti.objects.RTTIObject.str(RTTIObject.java:49)
    at com.shade.decima.ui.data.viewer.model.dmf.DMFExporter.exportMaterial(DMFExporter.java:1244)
    at com.shade.decima.ui.data.viewer.model.dmf.DMFExporter.exportDSMeshData(DMFExporter.java:1217)
    at com.shade.decima.ui.data.viewer.model.dmf.DMFExporter.regularSkinnedMeshResourceToModel(DMFExporter.java:987)
    at com.shade.decima.ui.data.viewer.model.dmf.DMFExporter.exportRegularSkinnedMeshResource(DMFExporter.java:443)
    at com.shade.decima.ui.data.viewer.model.dmf.DMFExporter.exportResource(DMFExporter.java:130)
    at com.shade.decima.ui.data.viewer.model.dmf.DMFExporter.export(DMFExporter.java:106)
    at com.shade.decima.ui.data.viewer.model.dmf.DMFExporter.export(DMFExporter.java:93)
    at com.shade.decima.ui.data.viewer.model.ModelExportDialog.lambda$buttonPressed$2(ModelExportDialog.java:127)
    ... 7 more

**Comment by REDxEYE** [comment]
Make sure you set project type to directors cut and use dsdc types dump

**Comment by Jomixedyu** [comment]
> Make sure you set project type to directors cut and use dsdc types dump
thanks!
