### ISSUE TITLE
Death Stranding Audio extraction and playback corrupted

### ISSUE THREAD

**Issue by VolodymyrKorshak** [ShadelessFox/decima#71]
Hi, 
Thank you for such a wonderful tool <3 

I am trying to extract audio from Death Stranding in order to create a voiceover localization for it.
The workshop can't play the file at all, extraction fails with the same error. 

Problem is the re-encode step fails with an error IO error for some reason. 
[16884998810871792125.zip](https://github.com/user-attachments/files/16042641/16884998810871792125.zip)

[+] wem gets created (I suppose so, can't be certain)
[+] ogg  gets created (attached in archive above) 
[-] ffmpeg fails (fixed with manual cmd run below)

`java.io.IOException: Process finished with exit code 2

Error:
Could not open output file.
    at com.shade.platform.model.util.IOUtils.exec(IOUtils.java:291)
    at com.shade.decima.ui.data.viewer.audio.AudioPlayerUtils.extractFromWwise(AudioPlayerUtils.java:75)
    at com.shade.decima.ui.data.viewer.audio.AudioPlayerUtils.extractTrack(AudioPlayerUtils.java:57)
    at com.shade.decima.ui.data.viewer.audio.AudioPlayerPanel.lambda$setTrack$1(AudioPlayerPanel.java:138)
    at com.shade.platform.ui.dialogs.ProgressDialog$1.doInBackground(ProgressDialog.java:47)
    at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)`

Ok, I looked up what you are doing with the file itself and trying to continue the process manually.

`ffmpeg.exe -acodec vorbis -i .\9796839657855114707.ogg -ac 2  test.wav`

However there is something wrong with the output itself. 
Attaching zip-archive with input and result.

Can you help me out or is it too much to ask? 
Is it possible to replace Death Stranding voiceover files at all?

**Comment by ShadelessFox** [comment]
I will need to reproduce the issue to determine what's wrong:
- What is the file's full path?
- Is this the Director's Cut version of the game?

Additionally, please ensure you're using the correct codebooks for the `ww2ogg` utility. It should be a file called `packed_codebooks_aoTuV_603`.

I also highly recommend continuing our conversation on our Discord server; the link is in the readme.

**Comment by VolodymyrKorshak** [comment]
` should be a file called packed_codebooks_aoTuV_603.`
This way the part I was missing. I chose the wrong codebooks file. 

`Is this the Director's Cut version of the game?`
Yes

`What is the file's full path?`
I was trying the ds/sounds/wwise_cinematics_sound_resource/cs00/sq_cs00_s00000/sq_cs00_s00000_sound.core


`ds/sounds/wwise_cinematics_sound_resource/cs99/sq_cs99_s00600/sq_cs99_s00600_sound.core
`This one still does not work with the same error


`I also highly recommend continuing our conversation on our Discord server; the link is in the readme.
`Will join your discord, lets continue the conversation there.

Thank you
