### ISSUE TITLE
error occurred while exporting

### ISSUE THREAD

**Issue by zzy7417** [ShadelessFox/decima#77]
i'm tring to export a model from death stranding director's cut but some error oocurred.....kindly ask for help

![image](https://github.com/user-attachments/assets/7b933d41-853f-484f-9242-584afacfffdc)

java.lang.RuntimeException: java.lang.IllegalArgumentException: Class 'InvalidObject' has no field called 'EffectType'
    at com.shade.decima.ui.data.viewer.model.ModelExportDialog.lambda$buttonPressed$2(ModelExportDialog.java:145)
    at com.shade.platform.ui.dialogs.ProgressDialog$1.doInBackground(ProgressDialog.java:47)
    at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Class 'InvalidObject' has no field called 'EffectType'
    at com.shade.decima.model.rtti.RTTIClass.getField(RTTIClass.java:43)
    at com.shade.decima.model.rtti.objects.RTTIObject.get(RTTIObject.java:21)
    at com.shade.decima.model.rtti.objects.RTTIObject.str(RTTIObject.java:54)
    at com.shade.decima.ui.data.viewer.model.dmf.DMFExporter.exportMaterial(DMFExporter.java:1271)
    at com.shade.decima.ui.data.viewer.model.dmf.DMFExporter.exportDSMeshData(DMFExporter.java:1244)
    at com.shade.decima.ui.data.viewer.model.dmf.DMFExporter.regularSkinnedMeshResourceToModel(DMFExporter.java:1011)
    at com.shade.decima.ui.data.viewer.model.dmf.DMFExporter.exportRegularSkinnedMeshResource(DMFExporter.java:440)
    at com.shade.decima.ui.data.viewer.model.dmf.DMFExporter.exportResource(DMFExporter.java:136)
    at com.shade.decima.ui.data.viewer.model.dmf.DMFExporter.export(DMFExporter.java:112)
    at com.shade.decima.ui.data.viewer.model.dmf.DMFExporter.export(DMFExporter.java:96)
    at com.shade.decima.ui.data.viewer.model.ModelExportDialog.lambda$buttonPressed$2(ModelExportDialog.java:142)
    ... 7 more

**Comment by ShadelessFox** [comment]
Make sure you're using a correct project type for the game. If you have the Director's Cut edition of the game, your project's type **must be set** to Director's Cut.

**Comment by zzy7417** [comment]
thank you so much for the help!! 🖒+300
